### PR TITLE
docs fix spelling issues

### PR DESCRIPTION
**Pull request by Guayaba221**
Hey !
I fixed several spelling issues.
Br, Guayaba221.

### CODE REVIEW

**Review by woodruffw — APPROVED** [review]

**Comment by woodruffw** [comment]
Thanks @Guayaba221. Could you please sign the CLA so I can merge this?

**Comment by Guayaba221** [comment]
@woodruffw Hello! Can someone take a look at this pull request and merge it if everything looks good? Let me know if any adjustments are needed. Appreciate it!

**Comment by woodruffw** [comment]
> @woodruffw Hello! Can someone take a look at this pull request and merge it if everything looks good? Let me know if any adjustments are needed. Appreciate it!

I can't merge it until you sign the CLA, as mentioned above. Other than that it looks good to me, thanks!

**Comment by Guayaba221** [comment]
@woodruffw done !

**Review by woodruffw — APPROVED** [review]

**Pull request merged**
